### ISSUE TITLE
wrong nodejs version installation

### ISSUE THREAD

**Issue by littleskunk** [Storj/storj-automation#46]
```
root@bridge:~# source ~/.nvm/nvm.sh && nvm install stable && nvm use stable && nvm alias default stable
Downloading https://nodejs.org/dist/v6.3.1/node-v6.3.1-linux-x64.tar.gz...
######################################################################## 100.0%
Now using node v6.3.1 (npm v3.10.3)
Creating default alias: default -> stable (-> v6.3.1)
Now using node v6.3.1 (npm v3.10.3)
default -> stable (-> v6.3.1)
```

**Comment by littleskunk** [comment]
`apt-get install curl` would be nice

**Comment by littleskunk** [comment]
Hard coded nodejs version 4.4.7 is not perfect but it was a quick solution for me. Merge it and keep the issue open to find a better solution later.

**Comment by computeronix** [comment]
is there a link or a file that can be dynamically referenced of latest minimum versions for the dependencies?  If so can then parse and use that going forward

**Comment by bookchin** [comment]
Just use:

```
nvm install --lts
```

To get the latest long term support release, which is what we use.

**Comment by computeronix** [comment]
hmm on windows will need to actually download the actually nodejs build and apply it
in the core repo could you have a file that declares the min requirements of nodejs / git / python and then this file can be dynamically referenced?

**Comment by bookchin** [comment]
https://nodejs.org/dist/v4.5.0/node-v4.5.0-linux-x86.tar.xz

**Comment by bookchin** [comment]
Or whatever the link is on the nodejs.org homepage for windows

**Comment by computeronix** [comment]
https://github.com/Storj/storj-automation/pull/48
Fixed 👍

**Comment by computeronix** [comment]
https://github.com/Storj/storj-automation/pull/49
Fixed: Bridge script

**Comment by computeronix** [comment]
https://github.com/Storj/storj-automation/pull/50
Fixed: storjshare-cli script

**Comment by computeronix** [comment]
Added 
1.2
Git for Windows latest version is automatically detected and installed (if needed)

**Comment by computeronix** [comment]
Version 1.3
Supports for automatically updating Python based on the Major Branch (default 2)
